#!/bin/bash

################################################################
#                                                              #
# Instalador e atualizador do 4k Video Downloader no Slackware #
#                                                              #
# By Mauricio Ferrari                                          #
#                                                              #
#                                                              #
# Não precisa ser root.                                        #
#                                                              #
################################################################


dir="_Packages"
prg="4kvideodownloaderplus"
desk="$HOME/.local/share/applications"

[ -e "../_PACKAGES" ] && dir="../_PACKAGES" || mkdir -p "$dir" # Isso aqui é pra mim

cd "$dir"

cwd="$PWD"

link0="https://www.4kdownload.com/pt-br/downloads/9"

version="$(grep -Eom1 "([0-9]+[.]){2}[0-9]+" <(grep -A5 "4K Video Downloader+" <(links -dump "$link0")))"

link1="https://dl.4kdownload.com/app/4kvideodownloaderplus_${version}_amd64.tar.bz2"
link2="https://static.4kdownload.com/main/img/redesign/videodownloader.a855bb9dddb2.svg"
pkg=${link1##*/}

wget -c "$link1"

[ ! -e "$prg" ] && tar -jxvf "$pkg"

cd "$prg" || exit 0

[ ! -e "$prg.svg" ] && wget -O "$prg.svg" -c "$link2"

[ -e "$desk/$prg.desktop" ] && exit 0

echo "[Desktop Entry]
Name=4k Video Downloader
GenericName=4k Video Downloader
Comment=Video Downloader
Exec=$cwd/$prg/$prg.sh
Icon=$cwd/$prg/$prg.svg
Type=Application
Terminal=false
Categories=Application;Network;" > "$desk/$prg.desktop"

exit 0
