#!/bin/bash

#######################################################
#                                                     #
# Instalador e atualizador do VirtualBox no Slackware #
#                                                     #
# By Mauricio Ferrari                                 #
#                                                     #
#                                                     #
# Não precisa ser root.                               #
#                                                     #
#######################################################
