#!/bin/bash

##########################################################################
#                                                                        #
# Instalador e atualizador de pacotes do slapt-get e gslapt no Slackware #
#                                                                        #
# By Mauricio Ferrari                                                    #
#                                                                        #
#                                                                        #
# Precisa ser root.                                                      #
#                                                                        #
##########################################################################


[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

dir="_Packages"

[ -e "../_PACKAGES" ] && dir="../_PACKAGES" || { mkdir -p "$dir"; chown 1000:users "$dir"; } # Isso aqui é pra mim

cd "$dir"


: "$(grep "VERSION_ID" /etc/os-release)"; slackver="${_#*=}"

case "$(uname -m)" in
    x86_64) arch=64  ;;
      arm*) arch=arm ;;
esac

link0="https://software.jaos.org/slackpacks/slackware$arch-$slackver"

pkgs=( $(grep -Eom2 "([g]*slapt([-]get)*([/]|[-]))+([0-9][.]*)+[-]([aA-zZ]*[0-9]*[_]*)+[-][0-9]+[.]t[a-z]*z" <(links -dump "$link0/ChangeLog.txt")) )

cd "/var/log/packages"
lst=$(printf "%s\n" *)
cd -
i=0

for pkg in "${pkgs[0]#*/}" "${pkgs[1]#*/}"; {

    test -n "$(grep -Eo "${pkg%[.]*}" <<< "$lst")" && continue;

    wget -c "$link0/${pkgs[$i]}"

    [ -e "$pkg" ] && {
        chown 1000:users "$pkg"
        /sbin/upgradepkg --install-new "$pkg"
    } || true

    let i++;
}

exit 0
