#!/bin/bash

################################################################
#                                                              #
# Instalador e atualizador de pacotes do alienbob no Slackware #
#                                                              #
# By Mauricio Ferrari                                          #
#                                                              #
#                                                              #
# Não precisa ser root.                                        #
#                                                              #
################################################################
